### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by vaxl029** [zongwei007/firefly#1]
你好，运行后一开始没有错误，访问页面就报错了
日志如下：

```bash
> firefly@1.2.1 start
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module '@mdi/js'
Require stack:
- /app/.next/server/pages/index.js
- /app/node_modules/next/dist/server/require.js
- /app/node_modules/next/dist/server/next-server.js
- /app/node_modules/next/dist/server/next.js
- /app/node_modules/next/dist/server/lib/start-server.js
- /app/node_modules/next/dist/cli/next-start.js
- /app/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/app/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.2853 (/app/.next/server/pages/index.js:795:18)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:25:42)
    at /app/.next/server/chunks/676.js:212:65
    at Function.__webpack_require__.a (/app/.next/server/webpack-runtime.js:103:13)
    at Object.4994 (/app/.next/server/chunks/676.js:201:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/.next/server/pages/index.js',
    '/app/node_modules/next/dist/server/require.js',
    '/app/node_modules/next/dist/server/next-server.js',
    '/app/node_modules/next/dist/server/next.js',
    '/app/node_modules/next/dist/server/lib/start-server.js',
    '/app/node_modules/next/dist/cli/next-start.js',
    '/app/node_modules/next/dist/bin/next'
  ]
}
npm notice 
npm notice New minor version of npm available! 8.5.5 -> 8.12.1
npm notice Changelog: 
npm notice Run `npm install -g npm@8.12.1` to update!
npm notice 
```

**Comment by vaxl029** [comment]
- -，不太会用docker，把@mdi/js模块装上去就好了

**Comment by zongwei007** [comment]
这个是镜像本身的问题，打包的时候为了节省空间多删了一个模块。现已修正，重新 pull 一下应该就可以了。

**Comment by vaxl029** [comment]
并不是一定需要webdav存储配置文件吧，我登陆后修改显示保存成功，但是找不到bookmarks.yml文件(有进入容器内部找过)
nignx反代的，没有上ssl

docker-compose.yml
```bash
version: '3'

services:
  firefly:
    container_name: "firefly"
    image: knives/firefly:latest
    ports:
      - "18391:3000"
    volumes:
      - "/home/url/data:/app/data"
    env_file:
      - .env
    restart: unless-stopped
```
.env
```bash
FIREFLY_TITLE=URL
FIREFLY_USERNAME=****
FIREFLY_PASSWORD=****
FIREFLY_DISABLE_LOGIN=false
DISK_PATH=/app/data
```

**Comment by zongwei007** [comment]
我使用 `sudo docker run --rm -p 3300:3000 -v /tmp:/app/data -e FIREFLY_DISABLE_LOGIN=true knives/firefly` 启动镜像，操作并保存，没有发现问题。

改了下代码新增了日志输出，你可以更新下试试，看看日志输出是否正常。

**Comment by vaxl029** [comment]
试了直接用这个```docker run --rm -p 18391:3000 -v /home/url/data:/app/data -e FIREFLY_DISABLE_LOGIN=false -e FIREFLY_USERNAME=**** -e FIREFLY_PASSWORD=**** knives/firefly```启动，没有输出异常的日志

登陆后，随便修改什么，比如添加个分类，保存完成，刷新页面又没有了

**Comment by vaxl029** [comment]
不好意思，我重新拉取镜像试试

**Comment by vaxl029** [comment]
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
使用本地磁盘存储，路径：/app/data
保存文件 /app/data/bookmarks.yml 失败 [Error: EACCES: permission denied, open '/app/data/bookmarks.yml'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/data/bookmarks.yml'
}
Unknown error [Error: EACCES: permission denied, open '/app/data/bookmarks.yml'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/data/bookmarks.yml'
}
UnknownException [Error]: EACCES: permission denied, open '/app/data/bookmarks.yml'
    at /app/.next/server/chunks/799.js:61:19
    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:185:9)
    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:395:9)
    at async Object.fn (/app/node_modules/next/dist/server/base-server.js:496:37)
    at async Router.execute (/app/node_modules/next/dist/server/router.js:226:36)
    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:606:29)
    at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:321:20) {
  code: 500,
  status: 500
}
```

应该是一开始就没有生成文件

```
root@VM-8-9-debian:~# docker container exec -it -u root cool_johnson /bin/sh
/app # ls
data            next.config.js  node_modules    package.json    public
/app # cd data
/app/data # ls
/app/data # 
```

**Comment by zongwei007** [comment]
文件访问权限不足。我这边平时不用 docker 跑这个……能否设置一下 `/home/url/data` 目录的读写权限？执行下 `chown 1001:1001 /home/url/data` 就行。
